### ISSUE TITLE
allocation form allows invalid combination of storage quota and then errors submission

### ISSUE THREAD

**Issue by bmb** [NeCTAR-RC/nectar-dashboard#1]
Currently it is possible to add a quota request for e.g. multiple volume zones, but the form doesn't filter out zones that have already been selected, so users can ask for quota in the same zone multiple times. This then seems to cause a model error and fails on submission.

**Comment by bmb** [comment]
initial report: https://support.nectar.org.au/helpdesk/tickets/1554

**Comment by sorrison** [comment]
Was fixed a while ago :-)
