### ISSUE TITLE
'allocation' filter is ignored when calling '/rest_api/chiefinvestigators/' endpoint

### ISSUE THREAD

**Issue by am-nash** [NeCTAR-RC/nectar-dashboard#11]
Likely due to drf viewset attribute 'filter_fields' having been renamed to 'filterset_fields'?

https://github.com/NeCTAR-RC/nectar-dashboard/blob/93e83e279886313c990aaa3de9717d1063e9619b/nectar_dashboard/rcallocation/api/allocation_extra.py#L56

https://www.django-rest-framework.org/api-guide/filtering/#djangofilterbackend

**Comment by sorrison** [comment]
This has been fixed
